export const ActionType = {
  FETCH_PROJECTS: 'FETCH_PROJECTS',
  FETCH_PROJECTS_FULFILLED: 'FETCH_PROJECTS_FULFILLED',
  FETCH_PROJECT_FULFILLED: 'FETCH_PROJECT_FULFILLED',
  FETCH_PROJECT: 'FETCH_PROJECT',
  CREATE_PROJECT: 'CREATE_PROJECT',
  UPDATE_PROJECT: 'UPDATE_PROJECT',
  REMOVE_PROJECT: 'REMOVE_PROJECT',
  FETCH_PROJECT_HEADER: 'FETCH_PROJECT_HEADER',
  FETCH_PROJECT_HEADER_FUL_FILLED: 'FETCH_PROJECT_HEADER_FUL_FILLED',
  UPDATE_PROJECT_HEADER: 'UPDATE_PROJECT_HEADER',
  REDIRECT_AFTER_CREATION: 'REDIRECT_AFTER_CREATION',
};
