export const ActionType = {
  FETCH_SETTING: 'FETCH_SETTING',
  FETCH_SETTING_FULFILLED: 'FETCH_SETTING_FULFILLED',
  UPDATE_SETTING: 'UPDATE_SETTING',
  REDIRECT_AFTER_UPDATE: 'REDIRECT_AFTER_UPDATE',
};
