export const ActionType = {
  SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',
  REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
  SHOW_LOADER: 'SHOW_LOADER',
  FETCH_NOTIFICATION: 'FETCH_NOTIFICATION',
  FETCH_NOTIFICATION_FUL_FILLED: 'FETCH_NOTIFICATION_FUL_FILLED',
};
