export const ActionType = {
  FETCH_TECHNOLOGIESS: 'FETCH_TECHNOLOGIESS',
  FETCH_TECHNOLOGIESS_FULFILLED: 'FETCH_TECHNOLOGIESS_FULFILLED',
  FETCH_TECHNOLOGIES_FULFILLED: 'FETCH_TECHNOLOGIES_FULFILLED',
  FETCH_TECHNOLOGIES: 'FETCH_TECHNOLOGIES',
  CREATE_TECHNOLOGIES: 'CREATE_TECHNOLOGIES',
  UPDATE_TECHNOLOGIES: 'UPDATE_TECHNOLOGIES',
  REMOVE_TECHNOLOGIES: 'REMOVE_TECHNOLOGIES',
  FETCH_TECHNOLOGIES_HEADER: 'FETCH_TECHNOLOGIES_HEADER',
  FETCH_TECHNOLOGIES_HEADER_FUL_FILLED: 'FETCH_TECHNOLOGIES_HEADER_FUL_FILLED',
  UPDATE_TECHNOLOGIES_HEADER: 'UPDATE_TECHNOLOGIES_HEADER',
  REDIRECT_AFTER_CREATION: 'REDIRECT_AFTER_CREATION',
};
