export const ActionType = {
  FETCH_TECHNOLOGIES: 'FETCH_TECHNOLOGIES',
  FETCH_TECHNOLOGIES_FULFILLED: 'FETCH_TECHNOLOGIES_FULFILLED',
  FETCH_TECHNOLOGY_FULFILLED: 'FETCH_TECHNOLOGY_FULFILLED',
  FETCH_TECHNOLOGY: 'FETCH_TECHNOLOGY',
  CREATE_TECHNOLOGY: 'CREATE_TECHNOLOGY',
  UPDATE_TECHNOLOGY: 'UPDATE_TECHNOLOGY',
  REMOVE_TECHNOLOGY: 'REMOVE_TECHNOLOGY',
  FETCH_TECHNOLOGY_HEADER: 'FETCH_TECHNOLOGY_HEADER',
  FETCH_TECHNOLOGY_HEADER_FUL_FILLED: 'FETCH_TECHNOLOGY_HEADER_FUL_FILLED',
  UPDATE_TECHNOLOGY_HEADER: 'UPDATE_TECHNOLOGY_HEADER',
  REDIRECT_AFTER_CREATION: 'REDIRECT_AFTER_CREATION',
};
