export const ActionType = {
  FETCH_SERVICES: 'FETCH_SERVICES',
  FETCH_SERVICES_FULFILLED: 'FETCH_SERVICES_FULFILLED',
  FETCH_SERVICE_FULFILLED: 'FETCH_SERVICE_FULFILLED',
  FETCH_SERVICE: 'FETCH_SERVICE',
  CREATE_SERVICE: 'CREATE_SERVICE',
  UPDATE_SERVICE: 'UPDATE_SERVICE',
  REMOVE_SERVICE: 'REMOVE_SERVICE',
  FETCH_HEADER: 'FETCH_HEADER',
  FETCH_HEADER_FUL_FILLED: 'FETCH_HEADER_FUL_FILLED',
  UPDATE_HEADER: 'UPDATE_HEADER',
  REDIRECT_AFTER_CREATION: 'REDIRECT_AFTER_CREATION',
};
