export const ActionType = {
  FETCH_COUNTERS: 'FETCH_COUNTERS',
  FETCH_COUNTERS_FULFILLED: 'FETCH_COUNTERS_FULFILLED',
  FETCH_COUNTER_FULFILLED: 'FETCH_COUNTER_FULFILLED',
  FETCH_COUNTER: 'FETCH_COUNTER',
  CREATE_COUNTER: 'CREATE_COUNTER',
  UPDATE_COUNTER: 'UPDATE_COUNTER',
  REMOVE_COUNTER: 'REMOVE_COUNTER',
  REDIRECT_AFTER_CREATION: 'REDIRECT_AFTER_CREATION',
};
