export const ActionType = {
  FETCH_TESTIMONIALS: 'FETCH_TESTIMONIALS',
  FETCH_TESTIMONIALS_FULFILLED: 'FETCH_TESTIMONIALS_FULFILLED',
  FETCH_TESTIMONIAL_FULFILLED: 'FETCH_TESTIMONIAL_FULFILLED',
  FETCH_TESTIMONIAL: 'FETCH_TESTIMONIAL',
  CREATE_TESTIMONIAL: 'CREATE_TESTIMONIAL',
  UPDATE_TESTIMONIAL: 'UPDATE_TESTIMONIAL',
  REMOVE_TESTIMONIAL: 'REMOVE_TESTIMONIAL',
  FETCH_TESTIMONIAL_HEADER: 'FETCH_TESTIMONIAL_HEADER',
  FETCH_TESTIMONIAL_HEADER_FUL_FILLED: 'FETCH_TESTIMONIAL_HEADER_FUL_FILLED',
  UPDATE_TESTIMONIAL_HEADER: 'UPDATE_TESTIMONIAL_HEADER',
  REDIRECT_AFTER_CREATION: 'REDIRECT_AFTER_CREATION',
};
